language: python

python:
    - 2.7

virtualenv:
    system_site_packages: true

before_install:
    - sh bin/check_signoff.sh

install:
    - git clone --branch demo git://github.com/cbmi/harvest-openmrs.git
    - pip install -r harvest-openmrs/requirements.txt
    - pip install uwsgi
    - npm install -g grunt-cli
    - npm install

before_script:
    - uwsgi --enable-threads \
        --protocol=http \
        --socket=127.0.0.1:8000 \
        --max-requests=5000 \
        --file=harvest-openmrs/wsgi.py \
        --socket=harvest-openmrs/uwsgi.sock \
        --chmod=660 &

script:
    - grunt test --verbose
